apiVersion: 1

datasources:
  - name: InfluxDB (bankdash)
    uid: influx-main
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: $INFLUXDB_BUCKET
    secureJsonData:
      token: $INFLUXDB_TOKEN
    editable: false
